// Generated by CoffeeScript 1.10.0
(function() {
  var Tiler, debug, defer, expect;

  expect = require("chai").expect;

  Tiler = require('../lib/Chillman');

  defer = require('node-promise').defer;

  debug = process.env['DEBUG'];

  describe("Chillman test", function() {
    before(function(done) {
      return done();
    });
    return it("should work", function(done) {
      expect(true).to.equal(true);
      return done();
    });
  });

}).call(this);

//# sourceMappingURL=chillman-spec.js.map
