// Generated by CoffeeScript 1.9.3
(function() {
  var Chillman, debug, defer, expect;

  expect = require("chai").expect;

  Chillman = require('../lib/Chillman');

  defer = require('node-promise').defer;

  debug = process.env['DEBUG'];

  describe("Chillman test", function() {
    before(function(done) {
      return done();
    });
    it("should pause a second request before the first is completed and have both return same value", function(done) {
      var count, landing, results, scarceResource, scarcecounter;
      scarcecounter = 0;
      scarceResource = function(key) {
        var q;
        q = defer();
        setTimeout(function() {
          var rv;
          rv = key + '_' + (scarcecounter++);
          return q.resolve(rv);
        }, 50);
        return q;
      };
      count = 0;
      results = [];
      landing = function(result) {
        results.push(result);
        if (++count === 2) {
          expect(results[0]).to.equal(results[1]);
          return done();
        }
      };
      Chillman.lookup(11, 'foo', scarceResource).then(landing);
      return Chillman.lookup(11, 'foo', scarceResource).then(landing);
    });
    return it("should make sure that requests of different types are kept separate, even if done close together", function(done) {
      var count, landing, results, scarceResource;
      scarceResource = function(key, type) {
        var q;
        q = defer();
        setTimeout(function() {
          var rv;
          rv = type + '_' + key;
          return q.resolve(rv);
        }, 50);
        return q;
      };
      count = 0;
      results = [];
      landing = function(result) {
        results.push(result);
        if (++count === 2) {
          expect(results[0].indexOf('bar')).to.equal(-1);
          expect(results[1].indexOf('foo')).to.equal(-1);
          return done();
        }
      };
      Chillman.lookup(11, 'foo', scarceResource).then(landing);
      return Chillman.lookup(19, 'bar', scarceResource).then(landing);
    });
  });

}).call(this);

//# sourceMappingURL=chillman-spec.js.map
