// Generated by CoffeeScript 1.9.3
(function() {
  var Chillman, defer, lru;

  defer = require('node-promise').defer;

  lru = require('lru');

  Chillman = (function() {
    function Chillman() {}

    Chillman.underwayCache = new lru();

    Chillman.callbackCache = new lru();

    Chillman.lookup = function(key, type, resolveFunc) {
      var callbacks, q, underway;
      q = defer();
      underway = Chillman.underwayCache.get(key + '_' + type);
      if (underway) {
        callbacks = Chillman.callbackCache.get(key + '_' + type) || [];
        callbacks.push(q);
        Chillman.callbackCache.set(key + '_' + type, callbacks);
      } else {
        Chillman.underwayCache.set(key + '_' + type, true);
        Chillman._doLookup(key, type, resolveFunc, q);
      }
      return q;
    };

    Chillman._doLookup = function(key, type, resolveFunc, q) {
      return resolveFunc(key, type).then(function(result) {
        var callbacks, cbcount;
        Chillman.underwayCache.remove(key + '_' + type);
        callbacks = Chillman.callbackCache.get(key + '_' + type) || [];
        cbcount = callbacks.length;
        callbacks.forEach(function(_q) {
          _q.resolve(result);
          if (--cbcount === 0) {
            return Chillman.callbackCache.remove(key + '_' + type);
          }
        });
        return q.resolve(result);
      });
    };

    return Chillman;

  })();

  module.exports = Chillman;

}).call(this);

//# sourceMappingURL=Chillman.js.map
