// Generated by CoffeeScript 1.10.0
(function() {
  var Chillman, defer, lru;

  defer = require('node-promise').defer;

  lru = require('lru');

  Chillman = (function() {
    function Chillman() {}

    Chillman.underwayCache = new lru();

    Chillman.callbackCache = new lru();

    Chillman.lookup = function(key, resolveFunc) {
      var callbacks, q, underway;
      q = defer();
      underway = Chillman.underwayCache.get(key);
      if (underway) {
        callbacks = Chillman.callbackCache[key] || [];
        callbacks.push(q);
        Chillman.callbackCache[key] = callbacks;
      } else {
        Chillman.underwayCache.set(key, true);
        Chillman._doLookup(key, resolveFunc, q);
      }
      return q;
    };

    Chillman._doLookup = function(key, resolveFunc, q) {
      return resolveFunc(key).then(function(result) {
        var callbacks;
        Chillman.underwayCache.remove(key);
        callbacks = Chillman.callbackCache[key] || [];
        callbacks.forEach(function(_q) {
          return _q.resolve(result);
        });
        return q.resolve(result);
      });
    };

    return Chillman;

  })();

  module.exports = Chillman;

}).call(this);

//# sourceMappingURL=Chillman.js.map
